package net.neoforged.bus;

import net.neoforged.bus.api.EventListener;

/**
 * A {@link EventListener} which is generated by {@link EventListener}.
 */
public non-sealed abstract class AbstractEventListenerImpl extends EventListener {
    AbstractEventListenerImpl() {
    }
}
